name: CI

on:
  push:
    branches: [ web ]
  pull_request:
    branches: [ web ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Slug
      - run: echo Hello, world!
